// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.0.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace csharp.Feature
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("Soundex algorithm", SourceFile="Feature/soundex.feature", SourceLine=0)]
    public partial class SoundexAlgorithmFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "soundex.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Soundex algorithm", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void AWordIsGivenToSoundexAlgorithm1(string word, string encoded, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A word is given to soundex algorithm 1", exampleTags);
#line 3
  this.ScenarioSetup(scenarioInfo);
#line 4
    testRunner.Given("A soundex instance", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 5
    testRunner.When(string.Format("I enter a word as \"{0}\"", word), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 6
    testRunner.Then(string.Format("it is encoded to \"{0}\"", encoded), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("A word is given to soundex algorithm 1, Variant 0", SourceLine=11)]
        public virtual void AWordIsGivenToSoundexAlgorithm1_Variant0()
        {
            this.AWordIsGivenToSoundexAlgorithm1("A", "A000", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("A word is given to soundex algorithm 1, Variant 1", SourceLine=11)]
        public virtual void AWordIsGivenToSoundexAlgorithm1_Variant1()
        {
            this.AWordIsGivenToSoundexAlgorithm1("I", "I000", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("A word is given to soundex algorithm 1, Variant 2", SourceLine=11)]
        public virtual void AWordIsGivenToSoundexAlgorithm1_Variant2()
        {
            this.AWordIsGivenToSoundexAlgorithm1("Ab", "A100", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("A word is given to soundex algorithm 1, Variant 3", SourceLine=11)]
        public virtual void AWordIsGivenToSoundexAlgorithm1_Variant3()
        {
            this.AWordIsGivenToSoundexAlgorithm1("Ac", "A200", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("A word is given to soundex algorithm 1, Variant 4", SourceLine=11)]
        public virtual void AWordIsGivenToSoundexAlgorithm1_Variant4()
        {
            this.AWordIsGivenToSoundexAlgorithm1("Ad", "A300", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("A word is given to soundex algorithm 1, Variant 5", SourceLine=11)]
        public virtual void AWordIsGivenToSoundexAlgorithm1_Variant5()
        {
            this.AWordIsGivenToSoundexAlgorithm1("Ax", "A200", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("A word is given to soundex algorithm 1, Variant 6", SourceLine=11)]
        public virtual void AWordIsGivenToSoundexAlgorithm1_Variant6()
        {
            this.AWordIsGivenToSoundexAlgorithm1("A#", "A000", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("A word is given to soundex algorithm 1, Variant 7", SourceLine=11)]
        public virtual void AWordIsGivenToSoundexAlgorithm1_Variant7()
        {
            this.AWordIsGivenToSoundexAlgorithm1("Acdl", "A234", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("A word is given to soundex algorithm 1, Variant 8", SourceLine=11)]
        public virtual void AWordIsGivenToSoundexAlgorithm1_Variant8()
        {
            this.AWordIsGivenToSoundexAlgorithm1("Baeiouhycdl", "B234", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("A word is given to soundex algorithm 1, Variant 9", SourceLine=11)]
        public virtual void AWordIsGivenToSoundexAlgorithm1_Variant9()
        {
            this.AWordIsGivenToSoundexAlgorithm1("Abfcgdt", "A123", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("A word is given to soundex algorithm 1, Variant 10", SourceLine=11)]
        public virtual void AWordIsGivenToSoundexAlgorithm1_Variant10()
        {
            this.AWordIsGivenToSoundexAlgorithm1("BaAeEiIoOuUhHyYcdl", "B234", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("A word is given to soundex algorithm 1, Variant 11", SourceLine=11)]
        public virtual void AWordIsGivenToSoundexAlgorithm1_Variant11()
        {
            this.AWordIsGivenToSoundexAlgorithm1("Bbcd", "B230", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("A word is given to soundex algorithm 1, Variant 12", SourceLine=11)]
        public virtual void AWordIsGivenToSoundexAlgorithm1_Variant12()
        {
            this.AWordIsGivenToSoundexAlgorithm1("Jbob", "J110", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("A word is given to soundex algorithm 2", SourceLine=25)]
        public virtual void AWordIsGivenToSoundexAlgorithm2()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A word is given to soundex algorithm 2", ((string[])(null)));
#line 26
  this.ScenarioSetup(scenarioInfo);
#line 27
    testRunner.Given("A soundex instance", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 28
    testRunner.When("I enter the word \"Dcdlb\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 29
    testRunner.Then("the encoded length is equal to \"4\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("A word is given to soundex algorithm with lower case letter", SourceLine=30)]
        public virtual void AWordIsGivenToSoundexAlgorithmWithLowerCaseLetter()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A word is given to soundex algorithm with lower case letter", ((string[])(null)));
#line 31
  this.ScenarioSetup(scenarioInfo);
#line 32
    testRunner.Given("A soundex instance", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 33
    testRunner.When("I enter the lower case word \"abcd\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 34
    testRunner.Then("the encoded first letter is equal to \"A\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        public virtual void AWordIsGivenToSoundexAlgorithm3(string character, string other_Character, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A word is given to soundex algorithm 3", exampleTags);
#line 36
  this.ScenarioSetup(scenarioInfo);
#line 37
    testRunner.Given("A soundex instance", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 38
    testRunner.When(string.Format("I enter the character \"{0}\"", character), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 39
    testRunner.Then(string.Format("it is equal to other encoded character \"{0}\"", other_Character), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("A word is given to soundex algorithm 3, b", SourceLine=41)]
        public virtual void AWordIsGivenToSoundexAlgorithm3_B()
        {
            this.AWordIsGivenToSoundexAlgorithm3("b", "f", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("A word is given to soundex algorithm 3, c", SourceLine=41)]
        public virtual void AWordIsGivenToSoundexAlgorithm3_C()
        {
            this.AWordIsGivenToSoundexAlgorithm3("c", "g", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("A word is given to soundex algorithm 3, d", SourceLine=41)]
        public virtual void AWordIsGivenToSoundexAlgorithm3_D()
        {
            this.AWordIsGivenToSoundexAlgorithm3("d", "t", ((string[])(null)));
#line hidden
        }
        
        public virtual void AWordIsGivenToSoundexAlgorithm4(string @string, string other_String, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A word is given to soundex algorithm 4", exampleTags);
#line 46
  this.ScenarioSetup(scenarioInfo);
#line 47
    testRunner.Given("A soundex instance", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 48
    testRunner.When(string.Format("I enter the string \"{0}\"", @string), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 49
    testRunner.Then(string.Format("it is equal to other encoded string \"{0}\"", other_String), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("A word is given to soundex algorithm 4, BCDL", SourceLine=51)]
        public virtual void AWordIsGivenToSoundexAlgorithm4_BCDL()
        {
            this.AWordIsGivenToSoundexAlgorithm4("BCDL", "Bcdl", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
